[charts/spark-operator] fix indentation in the telemetry sidecar section
spotinst/bigdata-charts pull request #196
Opened 2024-04-09 22:06 UTC by Z4ck404

Follows https://github.com/spotinst/bigdata-charts/pull/190: 
- And fixes an indentation issue in the telemetry section in the spark operator deployment
- Fix the port number of the telemetry input config.

# Jira Ticket

https://spotinst.atlassian.net/browse/BGD-4866

# Demo

- `helm upgrade spark-operator-bdenv-v74 charts/spark-operator -n spot-system --debug --set telemetry.enabled=true`

# Checklist:
- [ ] I have filled relevant self assessment ([NodeJS](https://docs.google.com/forms/d/e/1FAIpQLSfl14u9AOBAmxVJ272tvO7XNuXE-EMvWaGcaRZalu1UAKB7RA/viewform), [Frontend](https://docs.google.com/forms/d/e/1FAIpQLSdiBPNKH81w_EkavihVL8Uwb0j7tP8PwJmLFYm2nCOQxz-1qw/viewform), [Backend](https://docs.google.com/forms/d/e/1FAIpQLSed_PsTJ5-XIWkFL6BSDE2AQRBVPmwc3PAmHZkUn-erzVI37Q/viewform?usp=sf_link))
- [ ] I have run ESlint on my changes and fixed all warnings and errors (**NodeJS & Frontend Services**)
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have validated all the requirements in the Jira task were answered
- [ ] I have all neccessary approvals for the design/mini design of this task
- [ ] I have approved the API changes and granular permission patterns (documentation subtask) (**For public services only**)

2024-04-10 09:43 UTC, ImpSy commented on charts/bigdata-telemetry/templates/thanos-receiver-service.yaml
> +    {{- include "bigdata-telemetry.labels" . | nindent 4 }}
why create a new service with the same name ?

2024-04-10 09:53 UTC, ImpSy commented on charts/spark-operator/charts/spark-operator/templates/telemetry_configmap.yaml
>        scrape_interval         5s
Also metric collection should be tied to `{{- if .Values.metrics.enable }}`

2024-04-10 09:53 UTC, ImpSy approved these changes

2024-04-10 09:54 UTC, ImpSy requested changes
I just want to wave my approve

2024-04-11 08:06 UTC, Z4ck404 commented on charts/bigdata-telemetry/templates/thanos-receiver-service.yaml
> +    {{- include "bigdata-telemetry.labels" . | nindent 4 }}
No reason, I wanted to follow the pattern that we have in the notebook-service: 
https://github.com/spotinst/bigdata-charts/blob/main/charts/bigdata-notebook-service/templates/service.yaml. 

I don't need it.

2024-04-11 09:57 UTC, Z4ck404 commented on charts/spark-operator/charts/spark-operator/templates/telemetry_configmap.yaml
>        scrape_interval         5s
Fixed

2024-04-11 09:59 UTC, ImpSy approved these changes

2024-04-11 10:17 UTC, merged