disable terminals
spotinst/bigdata-charts pull request #243
Opened 2024-11-08 13:59 UTC by sigmarkarl

## Jira ticket

https://spotinst.atlassian.net/browse/BGD-5956

## Description

Hiding terminal in jupyterlab. This is a cosmetic change and will be further handled in https://spotinst.atlassian.net/browse/BGD-5957

## Demo

The launcher now looks like

<img width="1300" alt="Screenshot 2024-11-08 at 13 57 54" src="https://github.com/user-attachments/assets/52f7ea10-c554-47a2-84fe-bf0c80cba6b6">

No terminals launcher visible

## Checklist
- [x] I have added a Jira ticket link
- [x] I have filled in the test plan
- [x] I have executed the tests and filled in the test results
- [x] I have updated/created relevant documentation

## How to test

See demo screenshot. The terminal launcher should no longer be visible on the jupyterlab launcher page.

2024-11-12 11:59 UTC, alextarasov-spot requested changes
this PR linked to the wrong Jira ticket.
Check the branch name

2024-11-14 15:50 UTC, ImpSy commented
@sigmarkarl This will be superseded by your PR in the jupyter-server repo right ?

2024-11-17 14:25 UTC, alextarasov-spot commented on charts/bigdata-notebook-workspace/Chart.yaml
`image tag` and `appVersion`?

2024-11-20 16:09 UTC, closed without merging

2024-11-20 16:09 UTC, sigmarkarl commented
we will remove the terminado and jupyter_server_terminals in our custom jupyterlab Dockerfile (bigdata-infrastructure) instead as other components might install terminado